-- Manual adjustments history — Admin "Points & Coins" controller.
-- Records every +/− tweak made from the Points & Coins tab: team points,
-- individual points and coin-wallet corrections. Readable by everyone so the
-- admin UI can show it with the anon key; writes require a staff JWT
-- (mirrors the glocal_ledger policies). Apply once with:
--   psql "$DATABASE_URL" -f adjust_history.sql

create table if not exists public.rv26_adjust_history (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('team', 'student')),
  target_id bigint,
  target_name text,
  kind text not null check (kind in ('points', 'coins')),
  delta integer not null,
  reason text,
  actor text,
  created_at timestamptz not null default now()
);

alter table public.rv26_adjust_history enable row level security;

create policy "adjust history readable by everyone" on public.rv26_adjust_history
  for select using (true);

create policy "adjust history staff inserts" on public.rv26_adjust_history
  for insert to anon, authenticated
  with check (public.rv26_role() in ('admin', 'store'));