-- Rendezvous '26 — seed the programme list (idempotent)
-- Run in Dashboard → SQL Editor, or let the Supabase MCP apply it.

insert into public.programs (section, stage, name, section_order, position)
values
  ('Minor', 'On Stage', 'TARTEEL', 1, 1),
  ('Minor', 'On Stage', 'ELOCUTION MALAYALAM', 1, 2),
  ('Minor', 'On Stage', 'ELOCUTION ENGLISH', 1, 3),
  ('Minor', 'On Stage', 'TALK MASTER ARABIC', 1, 4),
  ('Minor', 'On Stage', 'GROUP SONG', 1, 5),
  ('Minor', 'On Stage', 'MADH SONG', 1, 6),
  ('Minor', 'On Stage', 'TONGUE TALES', 1, 7),
  ('Minor', 'Off Stage', 'ESSAY MALAYALAM', 1, 1),
  ('Minor', 'Off Stage', 'ESSAY ENGLISH', 1, 2),
  ('Minor', 'Off Stage', 'STORY MALAYALAM', 1, 3),
  ('Minor', 'Off Stage', 'STORY ARABIC', 1, 4),
  ('Minor', 'Off Stage', 'POEM MALAYALAM', 1, 5),
  ('Minor', 'Off Stage', 'PYGMY POEM ENGLISH', 1, 6),
  ('Minor', 'Off Stage', 'BOOK TEST', 1, 7),
  ('Minor', 'Off Stage', 'WRITTEN TRANSLATION ENG-MAL', 1, 8),
  ('Minor', 'Off Stage', 'SUDOKU', 1, 9),
  ('Minor', 'Off Stage', 'WATERCOLORING', 1, 10),
  ('Minor', 'Off Stage', 'IMLA''', 1, 11),
  ('Minor', 'Off Stage', 'HANDWRITING ENGLISH', 1, 12),
  ('Minor', 'Off Stage', 'GRAMMAR MASTERY', 1, 13),
  ('Minor', 'Off Stage', 'MATHS RELAY', 1, 14),
  ('Minor', 'Off Stage', 'SWARF TEST', 1, 15),
  ('Minor', 'Off Stage', 'IBARATH READING', 1, 16),
  ('Minor', 'Off Stage', 'QUIZ', 1, 17),
  ('Minor', 'Off Stage', 'WORD GAME ARABIC (PADHAKKALARI)', 1, 18),
  ('Minor', 'Off Stage', 'HIFZUL QUR''AN', 1, 19),
  ('Premier', 'On Stage', 'ELOCUTION MALAYALAM', 2, 1),
  ('Premier', 'On Stage', 'ELOCUTION ARABIC', 2, 2),
  ('Premier', 'On Stage', 'DEVOTIONAL SONG', 2, 3),
  ('Premier', 'On Stage', 'TALK MASTER ENGLISH', 2, 4),
  ('Premier', 'On Stage', 'PAPER PRESENTATION ENGLISH', 2, 5),
  ('Premier', 'On Stage', 'MADH SONG', 2, 6),
  ('Premier', 'On Stage', 'URUDU POEM RECITATION', 2, 7),
  ('Premier', 'Off Stage', 'ESSAY MALAYALAM', 2, 1),
  ('Premier', 'Off Stage', 'ESSAY ENGLISH', 2, 2),
  ('Premier', 'Off Stage', 'STORY MALAYALAM', 2, 3),
  ('Premier', 'Off Stage', 'STORY ENGLISH', 2, 4),
  ('Premier', 'Off Stage', 'POEM MALAYALAM', 2, 5),
  ('Premier', 'Off Stage', 'POEM ENGLISH', 2, 6),
  ('Premier', 'Off Stage', 'LETTERVERSE', 2, 7),
  ('Premier', 'Off Stage', 'PYGMY POEM ARABIC', 2, 8),
  ('Premier', 'Off Stage', 'BOOK TEST', 2, 9),
  ('Premier', 'Off Stage', 'WRITTEN TRANSLATION ENG-MAL', 2, 10),
  ('Premier', 'Off Stage', 'VOCABULARY ARABIC', 2, 11),
  ('Premier', 'Off Stage', 'WATERCOLORING', 2, 12),
  ('Premier', 'Off Stage', 'CARTOON SCAPE', 2, 13),
  ('Premier', 'Off Stage', 'CAPTION WRITING', 2, 14),
  ('Premier', 'Off Stage', 'IMLA', 2, 15),
  ('Premier', 'Off Stage', 'HANDWRITING ENGLISH', 2, 16),
  ('Premier', 'Off Stage', 'SUDOKU', 2, 17),
  ('Premier', 'Off Stage', 'QUIZ', 2, 18),
  ('Premier', 'Off Stage', 'NAHV TEST', 2, 19),
  ('Premier', 'Off Stage', 'SWARF TEST', 2, 20),
  ('Premier', 'Off Stage', 'IBARATH READING', 2, 21),
  ('Premier', 'Off Stage', 'HIFZUL MUTHOON', 2, 22),
  ('Premier', 'Off Stage', 'HIFZUL QUR''AN', 2, 23),
  ('Sub junior', 'On Stage', 'PUBLIC TALK ENGLISH', 3, 1),
  ('Sub junior', 'On Stage', 'ELOCUTION ARABIC', 3, 2),
  ('Sub junior', 'On Stage', 'ELOCUTION MALAYALAM', 3, 3),
  ('Sub junior', 'On Stage', 'HAMD UROU', 3, 4),
  ('Sub junior', 'On Stage', 'SONG ARABIC', 3, 5),
  ('Sub junior', 'On Stage', 'PAPER PRESENTATION ENGLISH', 3, 6),
  ('Sub junior', 'On Stage', 'MAPPILAPPATTU', 3, 7),
  ('Sub junior', 'Off Stage', 'ESSAY MALAYALAM', 3, 1),
  ('Sub junior', 'Off Stage', 'ESSAY ENGLISH', 3, 2),
  ('Sub junior', 'Off Stage', 'ESSAY ARABIC', 3, 3),
  ('Sub junior', 'Off Stage', 'ESSAY URDU', 3, 4),
  ('Sub junior', 'Off Stage', 'POEM MALAYALAM', 3, 5),
  ('Sub junior', 'Off Stage', 'POEM ENGLISH', 3, 6),
  ('Sub junior', 'Off Stage', 'POEM ARABIC', 3, 7),
  ('Sub junior', 'Off Stage', 'POEM URDU', 3, 8),
  ('Sub junior', 'Off Stage', 'STORY MALAYALAM', 3, 9),
  ('Sub junior', 'Off Stage', 'STORY ENGLISH', 3, 10),
  ('Sub junior', 'Off Stage', 'STORY ARABIC', 3, 11),
  ('Sub junior', 'Off Stage', 'STORY URDU', 3, 12),
  ('Sub junior', 'Off Stage', 'SOCIAL TWEET MALAYALAM', 3, 13),
  ('Sub junior', 'Off Stage', 'DICTIONARY MAKING ARB-ENG', 3, 14),
  ('Sub junior', 'Off Stage', 'WRITTEN TRANSLATION MAL-ENG', 3, 15),
  ('Sub junior', 'Off Stage', 'KITHABIC TEST', 3, 16),
  ('Sub junior', 'Off Stage', 'BOOK TEST', 3, 17),
  ('Sub junior', 'Off Stage', 'AD MAKING', 3, 18),
  ('Sub junior', 'Off Stage', 'IMLA', 3, 19),
  ('Sub junior', 'Off Stage', 'HIFZUL MUTHOON', 3, 20),
  ('Sub junior', 'Off Stage', 'QUIZ', 3, 21),
  ('Sub junior', 'Off Stage', 'SIARF TEST', 3, 22),
  ('Sub junior', 'Off Stage', 'NAHV TEST', 3, 23),
  ('Sub junior', 'Off Stage', 'WORD GAME ARABIC (PADHAKKALARI)', 3, 24),
  ('Sub junior', 'Off Stage', 'IBARATH READING', 3, 25),
  ('Sub junior', 'Off Stage', 'HIFZUL QUR''AN', 3, 26),
  ('General', 'On Stage', 'TARTEEL*', 4, 1),
  ('General', 'On Stage', 'OAWWALI', 4, 2),
  ('General', 'On Stage', 'NASHEEDA', 4, 3),
  ('General', 'On Stage', 'GROUP SONG', 4, 4),
  ('General', 'On Stage', 'NA''AT', 4, 5)
on conflict (section, stage, name) do nothing;