-- ============================================================
-- Rendezvous '26 — Supabase schema
-- Run this in the Supabase SQL editor (Dashboard → SQL Editor)
-- or with: supabase db execute --file supabase/schema.sql
-- ============================================================

-- ---------- Teams (live points leaderboard) ----------
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- Results (published result posters) ----------
create table if not exists public.results (
  id bigint generated by default as identity primary key,
  event_name text not null,
  category text,
  participant_name text,
  rank smallint,
  places jsonb,
  poster_path text not null,
  published boolean not null default false,
  points jsonb,
  created_at timestamptz not null default now()
);

alter table public.results add column if not exists places jsonb;

-- ---------- Gallery (captured photos) ----------
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  photo_path text not null,
  caption text,
  created_at timestamptz not null default now()
);

-- ---------- Festivita Points: students + ledger ----------
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  roster_no bigint unique,
  name text not null,
  team text,
  category text,
  qr_token text not null unique,
  points integer not null default 0,
  coins integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.glocal_ledger (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  delta integer not null,
  reason text,
  created_at timestamptz not null default now()
);

-- ---------- Realtime for live points ----------
alter table public.teams replica identity full;
alter table public.students replica identity full;

-- ---------- Row Level Security ----------
-- Reads are public. Writes are web-gated by the admin password in the UI.
-- For a tougher setup, connect Supabase Auth and restrict writes to
-- authenticated admin users instead.
alter table public.teams enable row level security;
alter table public.results enable row level security;
alter table public.gallery enable row level security;
alter table public.students enable row level security;
alter table public.glocal_ledger enable row level security;

create policy "teams readable by everyone" on public.teams
  for select using (true);
create policy "teams writable by anyone" on public.teams
  for all using (true) with check (true);

create policy "results readable by everyone" on public.results
  for select using (true);
create policy "results writable by anyone" on public.results
  for all using (true) with check (true);

create policy "gallery readable by everyone" on public.gallery
  for select using (true);
create policy "gallery writable by anyone" on public.gallery
  for all using (true) with check (true);

create policy "students readable by everyone" on public.students
  for select using (true);
create policy "students writable by anyone" on public.students
  for all using (true) with check (true);

create policy "glocal_ledger readable by everyone" on public.glocal_ledger
  for select using (true);
create policy "glocal_ledger writable by anyone" on public.glocal_ledger
  for all using (true) with check (true);

-- ---------- Programme list (sections, stages, events) ----------
create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  section text not null,
  stage text not null,
  name text not null,
  section_order integer not null default 0,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (section, stage, name)
);

alter table public.programs enable row level security;

create policy "programs readable by everyone" on public.programs
  for select using (true);
create policy "programs writable by anyone" on public.programs
  for all using (true) with check (true);
-- Seed data lives in supabase/programs_seed.sql

-- ---------- On Stage schedule (admin-managed) ----------
create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  day smallint not null,
  time text not null,
  title text not null,
  location text,
  tag text,
  position integer not null default 0,
  section text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.schedule enable row level security;

create policy "schedule readable by everyone" on public.schedule
  for select using (true);
create policy "schedule writable by anyone" on public.schedule
  for all using (true) with check (true);
-- Seed data lives in supabase/schedule_seed.sql

-- ---------- Storage buckets ----------
insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('results', 'results', true)
on conflict (id) do nothing;

create policy "public upload to gallery" on storage.objects
  for insert to anon with check (bucket_id = 'gallery');
create policy "public upload to results" on storage.objects
  for insert to anon with check (bucket_id = 'results');

-- ---------- Seed teams (idempotent) ----------
-- Teams drive the public leaderboard; add points from Admin → Teams.
insert into public.teams (name, points, updated_at)
select 'Isfahan Igniters', 0, now()
where not exists (select 1 from public.teams where name = 'Isfahan Igniters');

insert into public.teams (name, points, updated_at)
select 'Tanzanian Titans', 0, now()
where not exists (select 1 from public.teams where name = 'Tanzanian Titans');