-- ============================================================
-- Rendezvous '26 — Super Admin migration
-- Adds the owner-only audit trail and grants the 'super' role
-- every admin capability so the supervisor console can operate
-- (write) beside the existing staff roles.
--
-- Apply AFTER deploying verify-pin with SUPER_PIN_HASH:
--   supabase functions deploy verify-pin
--   supabase secrets set SUPER_PIN_HASH=<sha256 of "rv26:super:<pin>">
-- Then run this file in the Supabase SQL editor.
-- ============================================================

-- ---------- Audit trail (owner-only reads, staff appends) ----------
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor text not null default 'unknown',
  action text not null,
  entity_type text,
  entity_id text,
  entity_name text,
  detail jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;

create policy "audit readable by super only" on public.audit_log
  for select to anon, authenticated
  using (public.rv26_role() = 'super');

create policy "audit staff appends" on public.audit_log
  for insert to anon, authenticated
  with check (public.rv26_role() in ('admin', 'store', 'bookstall', 'super'));

-- ---------- Grant 'super' every admin capability ----------
create or replace function public.rv26_role() returns text
language sql stable
as $$
  select nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'rv26_role', '')
$$;

drop policy if exists "teams admin writes" on public.teams;
create policy "teams admin writes" on public.teams
  for all to anon, authenticated
  using (public.rv26_role() in ('admin', 'super'))
  with check (public.rv26_role() in ('admin', 'super'));

drop policy if exists "results admin writes" on public.results;
create policy "results admin writes" on public.results
  for all to anon, authenticated
  using (public.rv26_role() in ('admin', 'super'))
  with check (public.rv26_role() in ('admin', 'super'));

drop policy if exists "gallery admin writes" on public.gallery;
create policy "gallery admin writes" on public.gallery
  for all to anon, authenticated
  using (public.rv26_role() in ('admin', 'super'))
  with check (public.rv26_role() in ('admin', 'super'));

drop policy if exists "programs admin writes" on public.programs;
create policy "programs admin writes" on public.programs
  for all to anon, authenticated
  using (public.rv26_role() in ('admin', 'super'))
  with check (public.rv26_role() in ('admin', 'super'));

drop policy if exists "schedule admin writes" on public.schedule;
create policy "schedule admin writes" on public.schedule
  for all to anon, authenticated
  using (public.rv26_role() in ('admin', 'super'))
  with check (public.rv26_role() in ('admin', 'super'));

drop policy if exists "students staff insert" on public.students;
create policy "students staff insert" on public.students
  for insert to anon, authenticated
  with check (public.rv26_role() in ('admin', 'store', 'bookstall', 'super'));

drop policy if exists "students staff update" on public.students;
create policy "students staff update" on public.students
  for update to anon, authenticated
  using (public.rv26_role() in ('admin', 'store', 'bookstall', 'super'))
  with check (public.rv26_role() in ('admin', 'store', 'bookstall', 'super'));

drop policy if exists "students admin deletes" on public.students;
create policy "students admin deletes" on public.students
  for delete to anon, authenticated
  using (public.rv26_role() in ('admin', 'super'));

drop policy if exists "ledger staff inserts" on public.glocal_ledger;
create policy "ledger staff inserts" on public.glocal_ledger
  for insert to anon, authenticated
  with check (public.rv26_role() in ('admin', 'store', 'bookstall', 'super'));

drop policy if exists "ledger admin deletes" on public.glocal_ledger;
create policy "ledger admin deletes" on public.glocal_ledger
  for delete to anon, authenticated
  using (public.rv26_role() in ('admin', 'super'));

drop policy if exists "gallery admin uploads" on storage.objects;
create policy "gallery admin uploads" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'gallery' and public.rv26_role() in ('admin', 'super'));

drop policy if exists "gallery admin deletes" on storage.objects;
create policy "gallery admin deletes" on storage.objects
  for delete to authenticated
  using (bucket_id = 'gallery' and public.rv26_role() in ('admin', 'super'));

drop policy if exists "results admin uploads" on storage.objects;
create policy "results admin uploads" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'results' and public.rv26_role() in ('admin', 'super'));

drop policy if exists "results admin deletes" on storage.objects;
create policy "results admin deletes" on storage.objects
  for delete to authenticated
  using (bucket_id = 'results' and public.rv26_role() in ('admin', 'super'));