/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./js/*.js",
    "./css/*.css",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#A3E635",
        "on-primary": "#0B2412",
        "primary-container": "#82D128",
        "on-primary-container": "#0B2412",
        "primary-fixed": "#82D128",
        "primary-fixed-dim": "#A3E635",
        "on-primary-fixed": "#0B2412",
        "on-primary-fixed-variant": "#D0D7D1",
        "inverse-primary": "#82D128",
        "secondary": "#82D128",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#2A6B29",
        "on-secondary-container": "#FFFFFF",
        "secondary-fixed": "#A3E635",
        "secondary-fixed-dim": "#82D128",
        "on-secondary-fixed": "#FFFFFF",
        "on-secondary-fixed-variant": "#D0D7D1",
        "tertiary": "#A3E635",
        "on-tertiary": "#0B2412",
        "tertiary-container": "#2A6B29",
        "on-tertiary-container": "#FFFFFF",
        "tertiary-fixed": "#A3E635",
        "tertiary-fixed-dim": "#82D128",
        "on-tertiary-fixed": "#0B2412",
        "on-tertiary-fixed-variant": "#D0D7D1",
        "background": "#051910",
        "surface-dim": "#11131F",
        "surface": "#11131F",
        "surface-bright": "#1E2230",
        "surface-variant": "#181A26",
        "surface-container-lowest": "#11131F",
        "surface-container-low": "#141826",
        "surface-container": "#171B2C",
        "surface-container-high": "#181A26",
        "surface-container-highest": "#1E2230",
        "on-surface": "#FFFFFF",
        "on-background": "#FFFFFF",
        "on-surface-variant": "#D0D7D1",
        "inverse-surface": "#FFFFFF",
        "inverse-on-surface": "#11131F",
        "surface-tint": "#A3E635",
        "outline": "#6B7A6D",
        "outline-variant": "#2A3A2E",
        "error": "#F87171",
        "on-error": "#3B0000",
        "error-container": "#7F1D1D",
        "on-error-container": "#FECACA"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "margin-desktop": "3rem",
        "margin-mobile": "1.25rem",
        "space-3xl": "4rem",
        "space-sm": "0.75rem",
        "space-2xs": "0.25rem",
        "space-4xl": "6rem",
        "space-2xl": "3rem",
        "space-md": "1rem",
        "space-xs": "0.5rem"
      },
      fontFamily: {
        "label-code": ["JetBrains Mono"],
        "title-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Syne"],
        "display-hero-mobile": ["Syne"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Syne"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-hero": ["Syne"],
        "badge-caps": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Syne"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Syne"]
      },
      fontSize: {
        "label-code": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.08em", fontWeight: "500" }],
        "title-md": ["1.125rem", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.015em", fontWeight: "700" }],
        "display-hero-mobile": ["2.75rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["0.9375rem", { lineHeight: "1.6", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-sm": ["1.5rem", { lineHeight: "1.3", letterSpacing: "0em", fontWeight: "600" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-hero": ["5rem", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "800" }],
        "badge-caps": ["0.6875rem", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-xl-mobile": ["2rem", { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.65", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["3.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: []
};
